spring:
  application:
    name: beatckc
  datasource:
    username: "root"
    password: "YourNewP@ssw0rd!"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userInfo?createDatabaseIfNotExist=true
server:
  port: 8180
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: error
